# Generated by Django 3.0.2 on 2020-05-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsForRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('time_for_send', models.DateTimeField(verbose_name='Дата отправки уведомлений')),
                ('rang_todo', models.IntegerField(verbose_name='Категория отправленных задач')),
            ],
        ),
    ]
