# Generated by Django 3.0.2 on 2020-05-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsforrequest',
            name='rang_todo',
        ),
        migrations.RemoveField(
            model_name='settingsforrequest',
            name='time_for_send',
        ),
    ]
