# Generated by Django 2.2 on 2019-04-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=40, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Etalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etalon', models.CharField(db_index=True, max_length=40, verbose_name='Используемый эталон')),
            ],
            options={
                'verbose_name': 'Эталон',
                'verbose_name_plural': 'Эталоны',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, max_length=40, verbose_name='Методика')),
            ],
            options={
                'verbose_name': 'Методика',
                'verbose_name_plural': 'Методики',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(db_index=True, max_length=40, verbose_name='Место расположения счетчика')),
            ],
            options={
                'verbose_name': 'Место расположения',
                'verbose_name_plural': 'Места расположения счетчика',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_worker', models.CharField(db_index=True, max_length=150, verbose_name='fio_work')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес')),
                ('fio_client', models.CharField(max_length=150, verbose_name='ФИО клиента')),
                ('name_type', models.CharField(max_length=50, verbose_name='Наименование, тип СИ')),
                ('num_gos_reestr', models.CharField(max_length=15, verbose_name='№ гос. реестра')),
                ('num_fabric', models.CharField(max_length=25, verbose_name='Заводской номер')),
                ('pokazaniya', models.SmallIntegerField(verbose_name='Показания счетчика')),
                ('date_end_powerka', models.DateField(verbose_name='Срок окончания поверки')),
                ('num_svidet_powerka', models.CharField(max_length=25, verbose_name='№ св-ва о поверке')),
                ('result_powerka', models.BooleanField(verbose_name='Результат поверки(годен)')),
                ('qh', models.FloatField(verbose_name='Qh')),
                ('hot_water', models.BooleanField(verbose_name='Горячая вода')),
                ('plomba', models.BooleanField(verbose_name='Наличие пломбы')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.City', verbose_name='Город')),
                ('etalon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Etalon', verbose_name='Используемый эталон')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Method', verbose_name='Методика')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Place', verbose_name='Место расположения счетчика')),
            ],
            options={
                'verbose_name': 'Результат поверки',
                'verbose_name_plural': 'Поверки',
            },
        ),
    ]
