# Generated by Django 2.2 on 2019-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'ordering': ['-date'], 'verbose_name': 'Результат поверки', 'verbose_name_plural': 'Поверки'},
        ),
        migrations.AlterField(
            model_name='main',
            name='hot_water',
            field=models.IntegerField(choices=[(1, 'ДА'), (0, 'НЕТ')], verbose_name='Горячая вода'),
        ),
        migrations.AlterField(
            model_name='main',
            name='plomba',
            field=models.IntegerField(choices=[(1, 'ДА'), (0, 'НЕТ')], verbose_name='Наличие пломбы'),
        ),
        migrations.AlterField(
            model_name='main',
            name='result_powerka',
            field=models.IntegerField(choices=[(1, 'ДА'), (0, 'НЕТ')], verbose_name='Результат поверки(годен)'),
        ),
    ]
