# Generated by Django 2.2 on 2019-04-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190429_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='pokazaniya',
            field=models.CharField(max_length=25, verbose_name='Показания счетчика'),
        ),
    ]
