# Generated by Django 2.2 on 2019-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190430_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='city',
            field=models.ForeignKey(null=True, on_delete=models.SET('Нет данных'), to='data.City', verbose_name='Город'),
        ),
    ]
