# Generated by Django 2.2 on 2019-05-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190502_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.City', verbose_name='Город'),
        ),
    ]
