# Generated by Django 2.2 on 2019-05-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190502_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(db_index=True, max_length=140, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='etalon',
            name='etalon',
            field=models.CharField(db_index=True, max_length=140, verbose_name='Используемый эталон'),
        ),
        migrations.AlterField(
            model_name='main',
            name='adress',
            field=models.CharField(max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='main',
            name='fio_client',
            field=models.CharField(max_length=300, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='main',
            name='fio_worker',
            field=models.CharField(db_index=True, max_length=300, verbose_name='fio_work'),
        ),
        migrations.AlterField(
            model_name='main',
            name='name_type',
            field=models.CharField(max_length=150, verbose_name='Наименование, тип СИ'),
        ),
        migrations.AlterField(
            model_name='main',
            name='num_fabric',
            field=models.CharField(max_length=150, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='main',
            name='num_gos_reestr',
            field=models.CharField(max_length=50, verbose_name='№ гос. реестра'),
        ),
        migrations.AlterField(
            model_name='main',
            name='num_svidet_powerka',
            field=models.CharField(max_length=125, verbose_name='№ св-ва о поверке'),
        ),
        migrations.AlterField(
            model_name='main',
            name='pokazaniya',
            field=models.CharField(max_length=125, verbose_name='Показания счетчика'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method',
            field=models.CharField(db_index=True, max_length=140, verbose_name='Методика'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(db_index=True, max_length=140, verbose_name='Место расположения счетчика'),
        ),
    ]
