# Generated by Django 2.2.3 on 2019-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190509_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='hot_water',
            field=models.IntegerField(choices=[(1, 'Горячая'), (0, 'Холодная')], verbose_name='Вода'),
        ),
    ]
