# Generated by Django 2.2.3 on 2019-08-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20190813_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='num_telephone',
            field=models.CharField(blank=True, default=0, max_length=300, verbose_name='Номер телефона'),
        ),
    ]
