# Generated by Django 2.2.3 on 2019-09-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_main_num_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='view_svidet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.View_svidet', verbose_name='Серия свидетельства'),
        ),
    ]
