# Generated by Django 2.2.7 on 2019-11-16 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0010_auto_20190909_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(db_index=True, max_length=140, verbose_name='Интервал поверки')),
            ],
            options={
                'verbose_name': 'Интервал поверки',
                'verbose_name_plural': 'Интревал поверки',
            },
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'ordering': ['-date', '-published'], 'verbose_name': 'Результат поверки', 'verbose_name_plural': 'Поверки'},
        ),
        migrations.AddField(
            model_name='main',
            name='amp_filed',
            field=models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='№ АМП'),
        ),
        migrations.AlterField(
            model_name='main',
            name='fio_worker',
            field=models.CharField(db_index=True, max_length=300, verbose_name='ФИО работника'),
        ),
        migrations.CreateModel(
            name='DefaultForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etalon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Etalon', verbose_name='Используемый эталон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Пользователь')),
                ('view_svidet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.View_svidet', verbose_name='Серия свидетельства')),
            ],
            options={
                'verbose_name': 'Настройки по умолчанию для пользователя',
                'verbose_name_plural': 'Настройки по умолчанию для пользователя',
            },
        ),
        migrations.AddField(
            model_name='main',
            name='interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Interval', verbose_name='МПИ'),
        ),
    ]
