# Generated by Django 2.2.7 on 2019-11-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20191116_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultforuser',
            name='amp_boolean',
            field=models.BooleanField(default=False, verbose_name='Использовать номер антимагнитной пломбы'),
        ),
        migrations.AddField(
            model_name='defaultforuser',
            name='name_for_protokol',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Подписная часть протокола'),
        ),
        migrations.AddField(
            model_name='defaultforuser',
            name='protokol13',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Протокол строка 13'),
        ),
        migrations.AddField(
            model_name='defaultforuser',
            name='protokol14',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Протокол строка 14'),
        ),
        migrations.AddField(
            model_name='defaultforuser',
            name='protokol15',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Протокол строка 15'),
        ),
    ]
