version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend # maps host diretory to internal container directory
    working_dir: /backend/
    command: sh entrypoint.sh
    depends_on:
        - db-assistant

  frontend:
    image: node:12.7
    command: sh entrypoint.sh
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend


  nginx:
    image: nginx:latest
    ports:
      - 8181:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  db-assistant:
    image: postgres:11.4-alpine
    container_name: pgsql-assistant
    restart: on-failure
    environment:
      - POSTGRES_USER=assistant
      - POSTGRES_PASSWORD=max
    volumes:
      - ./docker-data/pgsql/data:/var/lib/postgresql/data

  adminer-assistant:
    image: adminer
    container_name: adminer-assistant
    restart: on-failure
    environment:
      ADMINER_DB: assistant
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: max
      ADMINER_SERVER: db-assistant
      ADMINER_USERNAME: assistant
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: adminer!
    depends_on:
      - db-assistant
