# Generated by Django 2.2.3 on 2019-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата установки')),
                ('fio_client', models.CharField(max_length=300, verbose_name='ФИО клиента')),
                ('phone', models.CharField(max_length=50, verbose_name='Контактный телефон')),
                ('adress', models.CharField(max_length=300, verbose_name='Адрес места эксплуатации (места установки)')),
                ('name_type', models.CharField(max_length=150, verbose_name='Тип (наименование) модель, счетчика')),
                ('num_fabric', models.CharField(max_length=150, verbose_name='Заводской номер')),
                ('pokazaniya', models.CharField(max_length=125, verbose_name='Текущие показания')),
                ('last_update', models.DateField(verbose_name='Последнее обновление показаний')),
                ('hot_water', models.IntegerField(choices=[(1, 'Горячая'), (0, 'Холодная')], verbose_name='Тип энергоресурса : вода Х/Г')),
                ('num_dogovor', models.CharField(db_index=True, max_length=300, verbose_name='Договор №')),
            ],
            options={
                'verbose_name': 'Результат ',
                'verbose_name_plural': 'Показания',
                'ordering': ['-date'],
            },
        ),
    ]
